project_id = "qcxjjhgfgyfhwacxppcp"

[functions.speech-to-text]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.openai-conversation]
verify_jwt = false

[functions.deduct-credits]
verify_jwt = true

[functions.ensure-credits]
verify_jwt = true
