// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcxjjhgfgyfhwacxppcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjeGpqaGdmZ3lmaHdhY3hwcGNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MjQ0NzMsImV4cCI6MjA3MzAwMDQ3M30.IJCtrmPDMyrLbzoL7iiF4koupkhHycBCKFZ6JGi11HA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});